esp_sntp: Fix c++ compile issue in esp_sntp.h
Added a cast to esp_sntp_operatingmode_t in sntp_setoperatingmode()'s
call to esp_sntp_setoperatingmode(operating_mode).  Althouogh C
doesn't require the cast, C++ does.  Otherwise you get...

error: invalid conversion from 'u8_t' {aka 'unsigned char'}
    to 'esp_sntp_operatingmode_t'